"""Yönetim paketi (frontend servis istekleri 14–18): toplantı ve gündem (meetings,
meeting_agenda_items), anket (polls, poll_options, poll_votes — gizli oy, bölüm başına bir oy),
hizmet sözleşmesi (contracts), demirbaş (assets), stok (stock_items, stock_moves — hareket
değişmez), site personeli (staff_members).

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-05 21:35:15.871200

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

TABLES = (
    "meetings",
    "meeting_agenda_items",
    "polls",
    "poll_options",
    "poll_votes",
    "contracts",
    "assets",
    "stock_items",
    "stock_moves",
    "staff_members",
)

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("acquired_on", sa.Date(), nullable=True),
        sa.Column("value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("assignee", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('in_use', 'broken', 'retired')", name=op.f("ck_assets_status")
        ),
        sa.CheckConstraint("value IS NULL OR value >= 0", name=op.f("ck_assets_value")),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_assets_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_assets_site_id_id")),
        sa.UniqueConstraint("site_id", "sequence", name=op.f("uq_assets_site_id_sequence")),
    )
    op.create_index(op.f("ix_assets_site_id"), "assets", ["site_id"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("vendor", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("period", sa.Text(), nullable=True),
        sa.Column("notice_days", sa.Integer(), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('elevator', 'cleaning', 'security', 'garden', 'maintenance', 'insurance', 'pool', 'other')",
            name=op.f("ck_contracts_category"),
        ),
        sa.CheckConstraint(
            "period IS NULL OR period IN ('monthly', 'yearly', 'once')",
            name=op.f("ck_contracts_period"),
        ),
        sa.CheckConstraint("amount IS NULL OR amount >= 0", name=op.f("ck_contracts_amount")),
        sa.CheckConstraint("end_date >= start_date", name=op.f("ck_contracts_dates")),
        sa.CheckConstraint("notice_days BETWEEN 0 AND 365", name=op.f("ck_contracts_notice_days")),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_contracts_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_contracts_site_id_id")),
    )
    op.create_index(op.f("ix_contracts_site_id"), "contracts", ["site_id"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attendance_note", sa.Text(), nullable=True),
        sa.Column("held_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("created_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('general_ordinary', 'general_extraordinary', 'board')",
            name=op.f("ck_meetings_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'held', 'cancelled')", name=op.f("ck_meetings_status")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_meetings_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_meetings_site_id_id")),
        sa.UniqueConstraint("site_id", "number", name=op.f("uq_meetings_site_id_number")),
    )
    op.create_index(op.f("ix_meetings_site_id"), "meetings", ["site_id"], unique=False)
    op.create_index(
        "ix_meetings_site_scheduled", "meetings", ["site_id", "scheduled_at"], unique=False
    )
    op.create_table(
        "polls",
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "audience IN ('all', 'owners', 'tenants')", name=op.f("ck_polls_audience")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_polls_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_polls")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_polls_site_id_id")),
    )
    op.create_index("ix_polls_site_ends", "polls", ["site_id", "ends_on"], unique=False)
    op.create_index(op.f("ix_polls_site_id"), "polls", ["site_id"], unique=False)
    op.create_table(
        "staff_members",
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("employer", sa.Text(), nullable=False),
        sa.Column("contractor_name", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("shift", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "employer <> 'contractor' OR contractor_name IS NOT NULL",
            name=op.f("ck_staff_members_contractor_name"),
        ),
        sa.CheckConstraint(
            "employer IN ('site', 'contractor')", name=op.f("ck_staff_members_employer")
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date", name=op.f("ck_staff_members_dates")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_staff_members_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_members")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_staff_members_site_id_id")),
    )
    op.create_index(op.f("ix_staff_members_site_id"), "staff_members", ["site_id"], unique=False)
    op.create_table(
        "stock_items",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_key", sa.Text(), nullable=False),
        sa.Column("unit_label", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("min_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("min_quantity >= 0", name=op.f("ck_stock_items_min_quantity")),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_stock_items_quantity_non_negative")),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_stock_items_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_items")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_stock_items_site_id_id")),
        sa.UniqueConstraint("site_id", "name_key", name=op.f("uq_stock_items_site_id_name_key")),
    )
    op.create_index(op.f("ix_stock_items_site_id"), "stock_items", ["site_id"], unique=False)
    op.create_table(
        "meeting_agenda_items",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("votes_for", sa.Integer(), nullable=True),
        sa.Column("votes_against", sa.Integer(), nullable=True),
        sa.Column("votes_abstain", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "result IS NULL OR result IN ('accepted', 'rejected', 'postponed', 'info')",
            name=op.f("ck_meeting_agenda_items_result"),
        ),
        sa.CheckConstraint(
            "COALESCE(votes_for, 0) >= 0 AND COALESCE(votes_against, 0) >= 0 AND COALESCE(votes_abstain, 0) >= 0",
            name=op.f("ck_meeting_agenda_items_votes_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "meeting_id"],
            ["meetings.site_id", "meetings.id"],
            name=op.f("fk_meeting_agenda_items_site_id_meeting_id_meetings"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_meeting_agenda_items_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_agenda_items")),
        sa.UniqueConstraint(
            "meeting_id", "order", name=op.f("uq_meeting_agenda_items_meeting_id_order")
        ),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_meeting_agenda_items_site_id_id")),
    )
    op.create_index(
        op.f("ix_meeting_agenda_items_meeting_id"),
        "meeting_agenda_items",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_agenda_items_site_id"), "meeting_agenda_items", ["site_id"], unique=False
    )
    op.create_table(
        "poll_options",
        sa.Column("poll_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id", "poll_id"],
            ["polls.site_id", "polls.id"],
            name=op.f("fk_poll_options_site_id_poll_id_polls"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_poll_options_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll_options")),
        sa.UniqueConstraint("poll_id", "order", name=op.f("uq_poll_options_poll_id_order")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_poll_options_site_id_id")),
    )
    op.create_index(op.f("ix_poll_options_poll_id"), "poll_options", ["poll_id"], unique=False)
    op.create_index(op.f("ix_poll_options_site_id"), "poll_options", ["site_id"], unique=False)
    op.create_table(
        "stock_moves",
        sa.Column("stock_item_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("moved_by", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("direction IN ('in', 'out')", name=op.f("ck_stock_moves_direction")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_moves_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["site_id", "stock_item_id"],
            ["stock_items.site_id", "stock_items.id"],
            name=op.f("fk_stock_moves_site_id_stock_item_id_stock_items"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_stock_moves_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_moves")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_stock_moves_site_id_id")),
    )
    op.create_index(
        "ix_stock_moves_item_created",
        "stock_moves",
        ["site_id", "stock_item_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_stock_moves_site_id"), "stock_moves", ["site_id"], unique=False)
    op.create_table(
        "poll_votes",
        sa.Column("poll_id", sa.Uuid(), nullable=False),
        sa.Column("option_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id", "option_id"],
            ["poll_options.site_id", "poll_options.id"],
            name=op.f("fk_poll_votes_site_id_option_id_poll_options"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "poll_id"],
            ["polls.site_id", "polls.id"],
            name=op.f("fk_poll_votes_site_id_poll_id_polls"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_poll_votes_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_poll_votes_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll_votes")),
        sa.UniqueConstraint("poll_id", "unit_id", name=op.f("uq_poll_votes_poll_id_unit_id")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_poll_votes_site_id_id")),
    )
    op.create_index(op.f("ix_poll_votes_poll_id"), "poll_votes", ["poll_id"], unique=False)
    op.create_index(op.f("ix_poll_votes_site_id"), "poll_votes", ["site_id"], unique=False)
    # ### end Alembic commands ###

    for table in TABLES:
        enable_tenant_rls(op, table)
    # Stok hareketi değişmez; yanlışsa ters hareket (forbid_history_change: göç 0008).
    op.execute(
        'CREATE TRIGGER stock_moves_immutable BEFORE UPDATE OR DELETE ON "stock_moves" '
        "FOR EACH ROW EXECUTE FUNCTION forbid_history_change()"
    )


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS stock_moves_immutable ON "stock_moves"')
    for table in reversed(TABLES):
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_poll_votes_site_id"), table_name="poll_votes")
    op.drop_index(op.f("ix_poll_votes_poll_id"), table_name="poll_votes")
    op.drop_table("poll_votes")
    op.drop_index(op.f("ix_stock_moves_site_id"), table_name="stock_moves")
    op.drop_index("ix_stock_moves_item_created", table_name="stock_moves")
    op.drop_table("stock_moves")
    op.drop_index(op.f("ix_poll_options_site_id"), table_name="poll_options")
    op.drop_index(op.f("ix_poll_options_poll_id"), table_name="poll_options")
    op.drop_table("poll_options")
    op.drop_index(op.f("ix_meeting_agenda_items_site_id"), table_name="meeting_agenda_items")
    op.drop_index(op.f("ix_meeting_agenda_items_meeting_id"), table_name="meeting_agenda_items")
    op.drop_table("meeting_agenda_items")
    op.drop_index(op.f("ix_stock_items_site_id"), table_name="stock_items")
    op.drop_table("stock_items")
    op.drop_index(op.f("ix_staff_members_site_id"), table_name="staff_members")
    op.drop_table("staff_members")
    op.drop_index(op.f("ix_polls_site_id"), table_name="polls")
    op.drop_index("ix_polls_site_ends", table_name="polls")
    op.drop_table("polls")
    op.drop_index("ix_meetings_site_scheduled", table_name="meetings")
    op.drop_index(op.f("ix_meetings_site_id"), table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_contracts_site_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_assets_site_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
