"""Talep (requests, request_events) ve duyuru (announcements, announcement_deliveries).

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-01 20:52:55.158531

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.

request_events değişmezdir: UPDATE/DELETE tetikleyiciyle reddedilir.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("requests", "request_events", "announcements", "announcement_deliveries")

_FORBID_CHANGE = """
CREATE OR REPLACE FUNCTION forbid_history_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Geçmiş kaydı değiştirilemez ve silinemez (%).', TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("importance", sa.Text(), nullable=False),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("audience_block_ids", sa.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("published_by", sa.Text(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "audience IN ('all_residents', 'blocks', 'owners_only', 'tenants_only', 'debtors_only')",
            name=op.f("ck_announcements_audience"),
        ),
        sa.CheckConstraint(
            "importance IN ('normal', 'important', 'critical')",
            name=op.f("ck_announcements_importance"),
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 3 AND 120", name=op.f("ck_announcements_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_announcements_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_announcements_site_id_id")),
    )
    op.create_index(op.f("ix_announcements_site_id"), "announcements", ["site_id"], unique=False)
    op.create_index(
        "ix_announcements_site_published",
        "announcements",
        ["site_id", "published_at"],
        unique=False,
    )
    op.create_table(
        "announcement_deliveries",
        sa.Column("announcement_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "channel IN ('in_app', 'web_push', 'email', 'sms')",
            name=op.f("ck_announcement_deliveries_channel"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "announcement_id"],
            ["announcements.site_id", "announcements.id"],
            name=op.f("fk_announcement_deliveries_site_id_announcement_id_announcements"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "person_id"],
            ["persons.site_id", "persons.id"],
            name=op.f("fk_announcement_deliveries_site_id_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_announcement_deliveries_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcement_deliveries")),
        sa.UniqueConstraint(
            "announcement_id",
            "person_id",
            "channel",
            name=op.f("uq_announcement_deliveries_announcement_id_person_id_channel"),
        ),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_announcement_deliveries_site_id_id")),
    )
    op.create_index(
        op.f("ix_announcement_deliveries_announcement_id"),
        "announcement_deliveries",
        ["announcement_id"],
        unique=False,
    )
    op.create_index(
        "ix_announcement_deliveries_person",
        "announcement_deliveries",
        ["site_id", "person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_announcement_deliveries_site_id"),
        "announcement_deliveries",
        ["site_id"],
        unique=False,
    )
    op.create_table(
        "requests",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("reported_by_person_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("assigned_to", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("created_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('other', 'plumbing', 'electrical', 'elevator', 'heating', 'cleaning', 'security', 'garden', 'common_area')",
            name=op.f("ck_requests_category"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')", name=op.f("ck_requests_priority")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'waiting', 'resolved', 'closed', 'cancelled')",
            name=op.f("ck_requests_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('resolved', 'closed') OR resolution IS NOT NULL",
            name=op.f("ck_requests_resolution_required"),
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 3 AND 120", name=op.f("ck_requests_title_length")
        ),
        sa.CheckConstraint("number > 0", name=op.f("ck_requests_number_positive")),
        sa.ForeignKeyConstraint(
            ["site_id", "reported_by_person_id"],
            ["persons.site_id", "persons.id"],
            name=op.f("fk_requests_site_id_reported_by_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_requests_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_requests_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requests")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_requests_site_id_id")),
        sa.UniqueConstraint("site_id", "number", name=op.f("uq_requests_site_id_number")),
    )
    op.create_index(
        "ix_requests_reporter", "requests", ["site_id", "reported_by_person_id"], unique=False
    )
    op.create_index(op.f("ix_requests_site_id"), "requests", ["site_id"], unique=False)
    op.create_index("ix_requests_site_status", "requests", ["site_id", "status"], unique=False)
    op.create_table(
        "request_events",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("actor_name", sa.Text(), nullable=True),
        sa.Column("new_status", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('created', 'status_changed', 'assigned', 'comment', 'resolved')",
            name=op.f("ck_request_events_kind"),
        ),
        sa.CheckConstraint(
            "new_status IS NULL OR new_status IN ('open', 'in_progress', 'waiting', 'resolved', 'closed', 'cancelled')",
            name=op.f("ck_request_events_new_status"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "request_id"],
            ["requests.site_id", "requests.id"],
            name=op.f("fk_request_events_site_id_request_id_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_request_events_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_events")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_request_events_site_id_id")),
    )
    op.create_index(
        op.f("ix_request_events_request_id"), "request_events", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_request_events_site_id"), "request_events", ["site_id"], unique=False)
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_tenant_rls(op, table)
    op.execute(_FORBID_CHANGE)
    op.execute(
        'CREATE TRIGGER request_events_immutable BEFORE UPDATE OR DELETE ON "request_events" '
        "FOR EACH ROW EXECUTE FUNCTION forbid_history_change()"
    )


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS request_events_immutable ON "request_events"')
    op.execute("DROP FUNCTION IF EXISTS forbid_history_change()")
    for table in TENANT_TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_events_site_id"), table_name="request_events")
    op.drop_index(op.f("ix_request_events_request_id"), table_name="request_events")
    op.drop_table("request_events")
    op.drop_index("ix_requests_site_status", table_name="requests")
    op.drop_index(op.f("ix_requests_site_id"), table_name="requests")
    op.drop_index("ix_requests_reporter", table_name="requests")
    op.drop_table("requests")
    op.drop_index(op.f("ix_announcement_deliveries_site_id"), table_name="announcement_deliveries")
    op.drop_index("ix_announcement_deliveries_person", table_name="announcement_deliveries")
    op.drop_index(
        op.f("ix_announcement_deliveries_announcement_id"), table_name="announcement_deliveries"
    )
    op.drop_table("announcement_deliveries")
    op.drop_index("ix_announcements_site_published", table_name="announcements")
    op.drop_index(op.f("ix_announcements_site_id"), table_name="announcements")
    op.drop_table("announcements")
    # ### end Alembic commands ###
