"""Tahsilat (payments) ve mahsup (payment_allocations).

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-01 00:06:12.461880

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.

payment_allocations değişmezdir (docs/04 §8): 0006'daki forbid_financial_change tetikleyicisi.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("payments", "payment_allocations")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("ledger_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("cash_account_id", sa.Uuid(), nullable=True),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "method IN ('cash', 'bank_transfer', 'credit_card', 'other')",
            name=op.f("ck_payments_method"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'cancelled')", name=op.f("ck_payments_status")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["site_id", "ledger_account_id"],
            ["ledger_accounts.site_id", "ledger_accounts.id"],
            name=op.f("fk_payments_site_id_ledger_account_id_ledger_accounts"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_payments_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_payments_site_id_id")),
    )
    op.create_index(
        "ix_payments_account", "payments", ["site_id", "ledger_account_id"], unique=False
    )
    op.create_index("ix_payments_site_date", "payments", ["site_id", "date"], unique=False)
    op.create_index(op.f("ix_payments_site_id"), "payments", ["site_id"], unique=False)
    op.create_table(
        "payment_allocations",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("ledger_entry_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payment_allocations_amount_positive")),
        sa.ForeignKeyConstraint(
            ["site_id", "ledger_entry_id"],
            ["ledger_entries.site_id", "ledger_entries.id"],
            name=op.f("fk_payment_allocations_site_id_ledger_entry_id_ledger_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "payment_id"],
            ["payments.site_id", "payments.id"],
            name=op.f("fk_payment_allocations_site_id_payment_id_payments"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_payment_allocations_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_allocations")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_payment_allocations_site_id_id")),
    )
    op.create_index(
        "ix_payment_allocations_entry",
        "payment_allocations",
        ["site_id", "ledger_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocations_payment_id"),
        "payment_allocations",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocations_site_id"), "payment_allocations", ["site_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_tenant_rls(op, table)
    op.execute(
        'CREATE TRIGGER payment_allocations_immutable BEFORE UPDATE OR DELETE ON "payment_allocations" '
        "FOR EACH ROW EXECUTE FUNCTION forbid_financial_change()"
    )


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS payment_allocations_immutable ON "payment_allocations"')
    for table in TENANT_TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_allocations_site_id"), table_name="payment_allocations")
    op.drop_index(op.f("ix_payment_allocations_payment_id"), table_name="payment_allocations")
    op.drop_index("ix_payment_allocations_entry", table_name="payment_allocations")
    op.drop_table("payment_allocations")
    op.drop_index(op.f("ix_payments_site_id"), table_name="payments")
    op.drop_index("ix_payments_site_date", table_name="payments")
    op.drop_index("ix_payments_account", table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
