"""Kullanıcı paketi: herkese açık uçların istek sınırı (rate_limits, global), sakin kayıt
bağlantısı (registration_links) ve başvuruları (registrations).

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-05 20:42:48.077229

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

TABLES = ("registration_links", "registrations")


revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("count >= 0", name=op.f("ck_rate_limits_count")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limits")),
        sa.UniqueConstraint("key", name=op.f("uq_rate_limits_key")),
    )
    op.create_index(
        op.f("ix_rate_limits_window_start"), "rate_limits", ["window_start"], unique=False
    )
    op.create_table(
        "registration_links",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_registration_links_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_links")),
        sa.UniqueConstraint("code", name=op.f("uq_registration_links_code")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_registration_links_site_id_id")),
        sa.UniqueConstraint("site_id", name=op.f("uq_registration_links_site_id")),
    )
    op.create_index(
        op.f("ix_registration_links_site_id"), "registration_links", ["site_id"], unique=False
    )
    op.create_table(
        "registrations",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("unit_text", sa.Text(), nullable=False),
        sa.Column("relation", sa.Text(), nullable=False),
        sa.Column("kvkk_ack_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("explicit_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_name", sa.Text(), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "relation IN ('owner', 'tenant')", name=op.f("ck_registrations_relation")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')", name=op.f("ck_registrations_status")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "person_id"],
            ["persons.site_id", "persons.id"],
            name=op.f("fk_registrations_site_id_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_registrations_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_registrations_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_registrations_site_id_id")),
        sa.UniqueConstraint("site_id", "number", name=op.f("uq_registrations_site_id_number")),
    )
    op.create_index(op.f("ix_registrations_site_id"), "registrations", ["site_id"], unique=False)
    op.create_index(
        "uq_registrations_pending_phone",
        "registrations",
        ["site_id", "phone"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###

    for table in TABLES:
        enable_tenant_rls(op, table)


def downgrade() -> None:
    for table in TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_registrations_pending_phone",
        table_name="registrations",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_registrations_site_id"), table_name="registrations")
    op.drop_table("registrations")
    op.drop_index(op.f("ix_registration_links_site_id"), table_name="registration_links")
    op.drop_table("registration_links")
    op.drop_index(op.f("ix_rate_limits_window_start"), table_name="rate_limits")
    op.drop_table("rate_limits")
    # ### end Alembic commands ###
