"""Pano özet tablosu (site_finance_summary) + mevcut veriden doldurma.

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-01 22:34:24.433099

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Doldurma tanımı servisle aynı: charged = geçerli koşuların borcu (dönemine göre),
# collected = onaylı tahsilat (tarihinin ayına göre). Göç sahibi de RLS'e tabi: tüm siteler.
_ALL_SITES = "SELECT set_config('app.all_sites', 'on', true)"
_BACKFILL = """
INSERT INTO site_finance_summary (id, site_id, year, month, charged, collected)
SELECT gen_random_uuid(), site_id, year, month, SUM(charged), SUM(collected)
FROM (
    SELECT c.site_id, p.year, p.month, c.amount AS charged, 0 AS collected
    FROM charges c
    JOIN charge_runs r ON r.site_id = c.site_id AND r.id = c.charge_run_id
    JOIN periods p ON p.site_id = r.site_id AND p.id = r.period_id
    WHERE r.status = 'posted' AND r.reversal_of_run_id IS NULL
    UNION ALL
    SELECT site_id, EXTRACT(YEAR FROM date)::int, EXTRACT(MONTH FROM date)::int, 0, amount
    FROM payments WHERE status = 'confirmed'
) AS rows
GROUP BY site_id, year, month
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_finance_summary",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("charged", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("collected", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "month BETWEEN 1 AND 12", name=op.f("ck_site_finance_summary_month_range")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_site_finance_summary_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_finance_summary")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_site_finance_summary_site_id_id")),
        sa.UniqueConstraint(
            "site_id", "year", "month", name=op.f("uq_site_finance_summary_site_id_year_month")
        ),
    )
    op.create_index(
        op.f("ix_site_finance_summary_site_id"), "site_finance_summary", ["site_id"], unique=False
    )
    # ### end Alembic commands ###

    enable_tenant_rls(op, "site_finance_summary")
    op.execute(_ALL_SITES)
    op.execute(_BACKFILL)


def downgrade() -> None:
    disable_tenant_rls(op, "site_finance_summary")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_finance_summary_site_id"), table_name="site_finance_summary")
    op.drop_table("site_finance_summary")
    # ### end Alembic commands ###
