"""Kargo (packages) ve ziyaretçi (visitors).

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-01 23:25:36.384255

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("carrier", sa.Text(), nullable=True),
        sa.Column("pickup_code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_by", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_by", sa.Text(), nullable=True),
        sa.Column("delivered_to", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("notification_sent", sa.Boolean(), nullable=False),
        sa.Column("notification_channel", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("pickup_code ~ '^[1-9][0-9]{3}$'", name=op.f("ck_packages_pickup_code")),
        sa.CheckConstraint(
            "status IN ('waiting', 'delivered', 'returned')", name=op.f("ck_packages_status")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "person_id"],
            ["persons.site_id", "persons.id"],
            name=op.f("fk_packages_site_id_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_packages_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_packages_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_packages_site_id_id")),
    )
    op.create_index(op.f("ix_packages_site_id"), "packages", ["site_id"], unique=False)
    op.create_index("ix_packages_site_status", "packages", ["site_id", "status"], unique=False)
    op.create_index("ix_packages_site_unit", "packages", ["site_id", "unit_id"], unique=False)
    op.create_table(
        "visitors",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("host_person_id", sa.Uuid(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("plate_number", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("qr_token", sa.Text(), nullable=True),
        sa.Column("expected_on", sa.Date(), nullable=True),
        sa.Column("visit_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_by", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('guest', 'cargo', 'service', 'contractor')", name=op.f("ck_visitors_kind")
        ),
        sa.CheckConstraint(
            "status IN ('expected', 'entered', 'exited', 'denied')", name=op.f("ck_visitors_status")
        ),
        sa.CheckConstraint(
            "char_length(full_name) BETWEEN 2 AND 80", name=op.f("ck_visitors_full_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "host_person_id"],
            ["persons.site_id", "persons.id"],
            name=op.f("fk_visitors_site_id_host_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_visitors_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_visitors_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visitors")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_visitors_site_id_id")),
    )
    op.create_index("ix_visitors_site_day", "visitors", ["site_id", "visit_date"], unique=False)
    op.create_index(op.f("ix_visitors_site_id"), "visitors", ["site_id"], unique=False)
    # ### end Alembic commands ###

    for table in ("packages", "visitors"):
        enable_tenant_rls(op, table)


def downgrade() -> None:
    for table in ("packages", "visitors"):
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_visitors_site_id"), table_name="visitors")
    op.drop_index("ix_visitors_site_day", table_name="visitors")
    op.drop_table("visitors")
    op.drop_index("ix_packages_site_unit", table_name="packages")
    op.drop_index("ix_packages_site_status", table_name="packages")
    op.drop_index(op.f("ix_packages_site_id"), table_name="packages")
    op.drop_table("packages")
    # ### end Alembic commands ###
