"""Platform (plans, organizations, sites) ve yapı (blocks, unit_types, units) tabloları.

Revision ID: 0001
Revises:
Create Date: 2026-09-30 20:43:21.882881

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("blocks", "unit_types", "units")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("max_units", sa.Integer(), nullable=True),
        sa.Column("max_storage_mb", sa.Integer(), nullable=True),
        sa.Column("allowed_modules", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("name", name=op.f("uq_plans_name")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("tax_number", sa.Text(), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 3 AND 150", name=op.f("ck_organizations_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_organizations_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "sites",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column("property_kind", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("fiscal_year_start_month", sa.Integer(), nullable=False),
        sa.Column("iban", sa.Text(), nullable=True),
        sa.Column("bank_name", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "property_kind IN ('residential', 'mixed', 'office', 'shopping_center')",
            name=op.f("ck_sites_property_kind"),
        ),
        sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_sites_slug_format")),
        sa.CheckConstraint(
            "fiscal_year_start_month BETWEEN 1 AND 12", name=op.f("ck_sites_fiscal_month")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sites_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], name=op.f("fk_sites_plan_id_plans")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("slug", name=op.f("uq_sites_slug")),
    )
    op.create_index(op.f("ix_sites_organization_id"), "sites", ["organization_id"], unique=False)
    op.create_table(
        "blocks",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("has_elevator", sa.Boolean(), nullable=False),
        sa.Column("floor_count", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_blocks_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocks")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_blocks_site_id_id")),
    )
    op.create_index(op.f("ix_blocks_site_id"), "blocks", ["site_id"], unique=False)
    op.create_table(
        "unit_types",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_unit_types_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_types")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_unit_types_site_id_id")),
    )
    op.create_index(op.f("ix_unit_types_site_id"), "unit_types", ["site_id"], unique=False)
    op.create_table(
        "units",
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Text(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("unit_type_id", sa.Uuid(), nullable=True),
        sa.Column("gross_area", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("net_area", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("land_share_numerator", sa.Integer(), nullable=True),
        sa.Column("land_share_denominator", sa.Integer(), nullable=True),
        sa.Column("usage", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("commercial_title", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "usage IN ('residential', 'commercial', 'storage', 'parking')",
            name=op.f("ck_units_usage"),
        ),
        sa.CheckConstraint(
            "(land_share_numerator IS NULL) = (land_share_denominator IS NULL)",
            name=op.f("ck_units_land_share_pair"),
        ),
        sa.CheckConstraint("floor BETWEEN -5 AND 100", name=op.f("ck_units_floor_range")),
        sa.CheckConstraint(
            "land_share_denominator IS NULL OR land_share_denominator > 0",
            name=op.f("ck_units_land_share_denominator"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "block_id"],
            ["blocks.site_id", "blocks.id"],
            name=op.f("fk_units_site_id_block_id_blocks"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_type_id"],
            ["unit_types.site_id", "unit_types.id"],
            name=op.f("fk_units_site_id_unit_type_id_unit_types"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_units_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint(
            "site_id", "block_id", "number", name=op.f("uq_units_site_id_block_id_number")
        ),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_units_site_id_id")),
    )
    op.create_index(op.f("ix_units_site_id"), "units", ["site_id"], unique=False)
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_tenant_rls(op, table)


def downgrade() -> None:
    for table in TENANT_TABLES:
        disable_tenant_rls(op, table)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_units_site_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_unit_types_site_id"), table_name="unit_types")
    op.drop_table("unit_types")
    op.drop_index(op.f("ix_blocks_site_id"), table_name="blocks")
    op.drop_table("blocks")
    op.drop_index(op.f("ix_sites_organization_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_table("organizations")
    op.drop_table("plans")
    # ### end Alembic commands ###
