"""Borçsuzluk belgesi (clearance_certificates) — değişmez (forbid_history_change, göç 0008).

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-03 12:40:39.792686

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clearance_certificates",
        sa.Column("ledger_account_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("number", sa.Text(), nullable=False),
        sa.Column("reference_code", sa.Text(), nullable=False),
        sa.Column("account_kind", sa.Text(), nullable=False),
        sa.Column("unit_name", sa.Text(), nullable=False),
        sa.Column("person_name", sa.Text(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("issued_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("issued_by_name", sa.Text(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("balance <= 0.005", name=op.f("ck_clearance_certificates_no_debt")),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_clearance_certificates_sequence_positive")
        ),
        sa.CheckConstraint(
            "valid_until >= as_of", name=op.f("ck_clearance_certificates_valid_after_as_of")
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            name=op.f("fk_clearance_certificates_issued_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "ledger_account_id"],
            ["ledger_accounts.site_id", "ledger_accounts.id"],
            name=op.f("fk_clearance_certificates_site_id_ledger_account_id_ledger_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_clearance_certificates_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearance_certificates")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_clearance_certificates_site_id_id")),
        sa.UniqueConstraint(
            "site_id", "number", name=op.f("uq_clearance_certificates_site_id_number")
        ),
        sa.UniqueConstraint(
            "site_id",
            "year",
            "sequence",
            name=op.f("uq_clearance_certificates_site_id_year_sequence"),
        ),
    )
    op.create_index(
        op.f("ix_clearance_certificates_ledger_account_id"),
        "clearance_certificates",
        ["ledger_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clearance_certificates_site_id"),
        "clearance_certificates",
        ["site_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    enable_tenant_rls(op, "clearance_certificates")
    op.execute(
        "CREATE TRIGGER clearance_certificates_immutable BEFORE UPDATE OR DELETE "
        "ON clearance_certificates "
        "FOR EACH ROW EXECUTE FUNCTION forbid_history_change()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS clearance_certificates_immutable ON clearance_certificates")
    disable_tenant_rls(op, "clearance_certificates")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clearance_certificates_site_id"), table_name="clearance_certificates")
    op.drop_index(
        op.f("ix_clearance_certificates_ledger_account_id"), table_name="clearance_certificates"
    )
    op.drop_table("clearance_certificates")
    # ### end Alembic commands ###
