"""Denetim kaydı (audit_log) — değişmez (forbid_history_change tetikleyicisi, göç 0008).

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-02 00:30:29.187288

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_name", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "action IN ('create', 'update', 'delete', 'import', 'download')",
            name=op.f("ck_audit_log_action"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_audit_log_site_id_sites")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_audit_log_site_id_id")),
    )
    op.create_index(
        "ix_audit_log_entity", "audit_log", ["site_id", "entity", "entity_id"], unique=False
    )
    op.create_index(
        "ix_audit_log_site_created", "audit_log", ["site_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_log_site_id"), "audit_log", ["site_id"], unique=False)
    # ### end Alembic commands ###

    enable_tenant_rls(op, "audit_log")
    op.execute(
        'CREATE TRIGGER audit_log_immutable BEFORE UPDATE OR DELETE ON "audit_log" '
        "FOR EACH ROW EXECUTE FUNCTION forbid_history_change()"
    )


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS audit_log_immutable ON "audit_log"')
    disable_tenant_rls(op, "audit_log")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_log_site_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_site_created", table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
