"""Kasa/banka (cash_accounts, cash_movements, cash_balances), gider (expenses), belge (stored_files).

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-01 21:29:18.308038

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.

Değişmezlik (docs/04 §8): cash_movements UPDATE/DELETE yok; expenses DELETE yok, yalnız ödeme
(bir kez) ve geri alındı işareti değişir. payments.cash_account_id artık cash_accounts'a bağlı.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("cash_accounts", "cash_movements", "cash_balances", "stored_files", "expenses")

_EXPENSES_GUARD = """
CREATE OR REPLACE FUNCTION expenses_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Gider kaydı silinemez; geri alma (ters kayıt) kullanın.'
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.amount IS DISTINCT FROM OLD.amount
       OR NEW.date IS DISTINCT FROM OLD.date
       OR NEW.description IS DISTINCT FROM OLD.description
       OR NEW.expense_category_id IS DISTINCT FROM OLD.expense_category_id
       OR NEW.period_id IS DISTINCT FROM OLD.period_id
       OR NEW.vendor IS DISTINCT FROM OLD.vendor
       OR NEW.document_number IS DISTINCT FROM OLD.document_number
       OR NEW.stored_file_id IS DISTINCT FROM OLD.stored_file_id
       OR NEW.reversal_of_id IS DISTINCT FROM OLD.reversal_of_id
       OR NEW.site_id IS DISTINCT FROM OLD.site_id
       OR (OLD.paid_on IS NOT NULL AND NEW.paid_on IS DISTINCT FROM OLD.paid_on)
       OR (OLD.cash_account_id IS NOT NULL
           AND NEW.cash_account_id IS DISTINCT FROM OLD.cash_account_id)
       OR (OLD.is_reversed AND NOT NEW.is_reversed) THEN
        RAISE EXCEPTION 'Giderin tutarı, tarihi ve açıklaması değiştirilemez; düzeltme ters kayıtla yapılır.'
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_accounts",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("bank_name", sa.Text(), nullable=True),
        sa.Column("iban", sa.Text(), nullable=True),
        sa.Column("opening_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('cash', 'bank')", name=op.f("ck_cash_accounts_kind")),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 2 AND 60", name=op.f("ck_cash_accounts_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_cash_accounts_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_accounts")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_cash_accounts_site_id_id")),
        sa.UniqueConstraint("site_id", "name", name=op.f("uq_cash_accounts_site_id_name")),
    )
    op.create_index(op.f("ix_cash_accounts_site_id"), "cash_accounts", ["site_id"], unique=False)
    op.create_table(
        "stored_files",
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=True),
        sa.Column("uploaded_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "content_type IN ('application/pdf', 'image/jpeg', 'image/png', 'image/webp')",
            name=op.f("ck_stored_files_content_type"),
        ),
        sa.CheckConstraint(
            "storage_path NOT LIKE '%..%'", name=op.f("ck_stored_files_storage_path")
        ),
        sa.CheckConstraint(
            "byte_size > 0 AND byte_size <= 10485760", name=op.f("ck_stored_files_byte_size")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_stored_files_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_stored_files_site_id_id")),
    )
    op.create_index(op.f("ix_stored_files_site_id"), "stored_files", ["site_id"], unique=False)
    op.create_table(
        "cash_balances",
        sa.Column("cash_account_id", sa.Uuid(), nullable=False),
        sa.Column("inflow_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("outflow_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id", "cash_account_id"],
            ["cash_accounts.site_id", "cash_accounts.id"],
            name=op.f("fk_cash_balances_site_id_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_cash_balances_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_balances")),
        sa.UniqueConstraint("cash_account_id", name=op.f("uq_cash_balances_cash_account_id")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_cash_balances_site_id_id")),
    )
    op.create_index(op.f("ix_cash_balances_site_id"), "cash_balances", ["site_id"], unique=False)
    op.create_table(
        "cash_movements",
        sa.Column("cash_account_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("inflow", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("outflow", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source IN ('manual', 'payment', 'expense', 'transfer', 'opening')",
            name=op.f("ck_cash_movements_source"),
        ),
        sa.CheckConstraint(
            "inflow >= 0 AND outflow >= 0 AND (inflow > 0) <> (outflow > 0)",
            name=op.f("ck_cash_movements_one_side"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "cash_account_id"],
            ["cash_accounts.site_id", "cash_accounts.id"],
            name=op.f("fk_cash_movements_site_id_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "reversal_of_id"],
            ["cash_movements.site_id", "cash_movements.id"],
            name=op.f("fk_cash_movements_site_id_reversal_of_id_cash_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_cash_movements_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movements")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_cash_movements_site_id_id")),
    )
    op.create_index(
        "ix_cash_movements_site_account_date",
        "cash_movements",
        ["site_id", "cash_account_id", "date"],
        unique=False,
    )
    op.create_index(op.f("ix_cash_movements_site_id"), "cash_movements", ["site_id"], unique=False)
    op.create_index(
        "ix_cash_movements_source", "cash_movements", ["site_id", "source_id"], unique=False
    )
    op.create_index(
        "uq_cash_movements_reversal_of",
        "cash_movements",
        ["reversal_of_id"],
        unique=True,
        postgresql_where="reversal_of_id IS NOT NULL",
    )
    op.create_table(
        "expenses",
        sa.Column("expense_category_id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("vendor", sa.Text(), nullable=True),
        sa.Column("document_number", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("stored_file_id", sa.Uuid(), nullable=True),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("cash_account_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("is_reversed", sa.Boolean(), nullable=False),
        sa.Column("created_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(paid_on IS NULL) = (cash_account_id IS NULL)",
            name=op.f("ck_expenses_paid_with_account"),
        ),
        sa.CheckConstraint(
            "(reversal_of_id IS NULL) = (amount > 0)", name=op.f("ck_expenses_reversal_negative")
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_expenses_amount_nonzero")),
        sa.CheckConstraint(
            "char_length(description) BETWEEN 3 AND 200",
            name=op.f("ck_expenses_description_length"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "cash_account_id"],
            ["cash_accounts.site_id", "cash_accounts.id"],
            name=op.f("fk_expenses_site_id_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "expense_category_id"],
            ["expense_categories.site_id", "expense_categories.id"],
            name=op.f("fk_expenses_site_id_expense_category_id_expense_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "period_id"],
            ["periods.site_id", "periods.id"],
            name=op.f("fk_expenses_site_id_period_id_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "reversal_of_id"],
            ["expenses.site_id", "expenses.id"],
            name=op.f("fk_expenses_site_id_reversal_of_id_expenses"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "stored_file_id"],
            ["stored_files.site_id", "stored_files.id"],
            name=op.f("fk_expenses_site_id_stored_file_id_stored_files"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_expenses_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_expenses_site_id_id")),
    )
    op.create_index("ix_expenses_site_date", "expenses", ["site_id", "date"], unique=False)
    op.create_index(op.f("ix_expenses_site_id"), "expenses", ["site_id"], unique=False)
    op.create_index(
        "uq_expenses_reversal_of",
        "expenses",
        ["reversal_of_id"],
        unique=True,
        postgresql_where="reversal_of_id IS NOT NULL",
    )
    op.create_foreign_key(
        op.f("fk_payments_site_id_cash_account_id_cash_accounts"),
        "payments",
        "cash_accounts",
        ["site_id", "cash_account_id"],
        ["site_id", "id"],
    )
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_tenant_rls(op, table)
    op.execute(
        'CREATE TRIGGER cash_movements_immutable BEFORE UPDATE OR DELETE ON "cash_movements" '
        "FOR EACH ROW EXECUTE FUNCTION forbid_financial_change()"
    )
    op.execute(_EXPENSES_GUARD)
    op.execute(
        'CREATE TRIGGER expenses_guard BEFORE UPDATE OR DELETE ON "expenses" '
        "FOR EACH ROW EXECUTE FUNCTION expenses_guard()"
    )


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS expenses_guard ON "expenses"')
    op.execute("DROP FUNCTION IF EXISTS expenses_guard()")
    op.execute('DROP TRIGGER IF EXISTS cash_movements_immutable ON "cash_movements"')
    for table in TENANT_TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_payments_site_id_cash_account_id_cash_accounts"), "payments", type_="foreignkey"
    )
    op.drop_index(
        "uq_expenses_reversal_of",
        table_name="expenses",
        postgresql_where="reversal_of_id IS NOT NULL",
    )
    op.drop_index(op.f("ix_expenses_site_id"), table_name="expenses")
    op.drop_index("ix_expenses_site_date", table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(
        "uq_cash_movements_reversal_of",
        table_name="cash_movements",
        postgresql_where="reversal_of_id IS NOT NULL",
    )
    op.drop_index("ix_cash_movements_source", table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_site_id"), table_name="cash_movements")
    op.drop_index("ix_cash_movements_site_account_date", table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index(op.f("ix_cash_balances_site_id"), table_name="cash_balances")
    op.drop_table("cash_balances")
    op.drop_index(op.f("ix_stored_files_site_id"), table_name="stored_files")
    op.drop_table("stored_files")
    op.drop_index(op.f("ix_cash_accounts_site_id"), table_name="cash_accounts")
    op.drop_table("cash_accounts")
    # ### end Alembic commands ###
