"""Operasyon paketi 2: güvenlik olay kaydı (incidents), kayıp eşya (lost_items), talep
departmanları (request_departments, requests.department_id) + mevcut sitelere varsayılan
departmanlar; talep geçmişine `department_changed` olay türü.

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-05 21:07:36.334648

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

TABLES = ("incidents", "lost_items", "request_departments")
_KINDS = ("created", "status_changed", "assigned", "comment", "resolved")
# Varsayılan departmanlar (services/departments.DEFAULTS); name_key ASCII-katlanmış küçük harf.
_DEFAULTS = (
    ("Teknik", "teknik"),
    ("Temizlik", "temizlik"),
    ("Güvenlik", "guvenlik"),
    ("Bahçe", "bahce"),
    ("Yönetim", "yonetim"),
)


def _kind_check(values: tuple[str, ...]) -> None:
    name = op.f("ck_request_events_kind")
    op.drop_constraint(name, "request_events", type_="check")
    allowed = ", ".join(f"'{v}'" for v in values)
    op.create_check_constraint(name, "request_events", f"kind IN ({allowed})")


revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lost_items",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("found_by", sa.Text(), nullable=True),
        sa.Column("found_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("returned_to", sa.Text(), nullable=True),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_by", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('waiting', 'returned', 'disposed')", name=op.f("ck_lost_items_status")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_lost_items_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lost_items")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_lost_items_site_id_id")),
        sa.UniqueConstraint("site_id", "number", name=op.f("uq_lost_items_site_id_number")),
    )
    op.create_index(op.f("ix_lost_items_site_id"), "lost_items", ["site_id"], unique=False)
    op.create_index(
        "ix_lost_items_site_status", "lost_items", ["site_id", "status", "found_at"], unique=False
    )
    op.create_table(
        "request_departments",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_key", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_request_departments_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_departments")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_request_departments_site_id_id")),
        sa.UniqueConstraint(
            "site_id", "name_key", name=op.f("uq_request_departments_site_id_name_key")
        ),
    )
    op.create_index(
        op.f("ix_request_departments_site_id"), "request_departments", ["site_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("closed_note", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Text(), nullable=True),
        sa.Column("recorded_by", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('theft', 'damage', 'noise', 'fire', 'water_leak', 'suspicious', 'accident', 'other')",
            name=op.f("ck_incidents_kind"),
        ),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_incidents_status")),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_incidents_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_incidents_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_incidents_site_id_id")),
        sa.UniqueConstraint("site_id", "number", name=op.f("uq_incidents_site_id_number")),
    )
    op.create_index(op.f("ix_incidents_site_id"), "incidents", ["site_id"], unique=False)
    op.create_index(
        "ix_incidents_site_status", "incidents", ["site_id", "status", "occurred_at"], unique=False
    )
    op.add_column("requests", sa.Column("department_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_requests_site_id_department_id_request_departments"),
        "requests",
        "request_departments",
        ["site_id", "department_id"],
        ["site_id", "id"],
    )
    # ### end Alembic commands ###

    for table in TABLES:
        enable_tenant_rls(op, table)
    _kind_check((*_KINDS, "department_changed"))
    # Göç sahibi de RLS'e tabi: bilinçli tüm siteler kapsamı.
    op.execute("SELECT set_config('app.all_sites', 'on', true)")
    for name, key in _DEFAULTS:
        op.execute(
            sa.text(
                "INSERT INTO request_departments (id, site_id, name, name_key, is_active) "
                "SELECT gen_random_uuid(), s.id, :name, :key, true FROM sites s "
                "ON CONFLICT (site_id, name_key) DO NOTHING"
            ).bindparams(name=name, key=key)
        )


def downgrade() -> None:
    _kind_check(_KINDS)  # department_changed olayı varsa durur (geçmiş silinmez)
    for table in TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_requests_site_id_department_id_request_departments"),
        "requests",
        type_="foreignkey",
    )
    op.drop_column("requests", "department_id")
    op.drop_index("ix_incidents_site_status", table_name="incidents")
    op.drop_index(op.f("ix_incidents_site_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_request_departments_site_id"), table_name="request_departments")
    op.drop_table("request_departments")
    op.drop_index("ix_lost_items_site_status", table_name="lost_items")
    op.drop_index(op.f("ix_lost_items_site_id"), table_name="lost_items")
    op.drop_table("lost_items")
    # ### end Alembic commands ###
