"""Otomatik aylık tahakkuk: ayar (charge_schedules) ve ay başına sonuç (charge_schedule_runs).

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-03 12:55:21.071482

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

TABLES = ("charge_schedules", "charge_schedule_runs")


revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charge_schedules",
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("charge_day", sa.Integer(), nullable=False),
        sa.Column("due_days", sa.Integer(), nullable=False),
        sa.Column("notify_on_run", sa.Boolean(), nullable=False),
        sa.Column("enabled_on", sa.Date(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "charge_day BETWEEN 1 AND 28", name=op.f("ck_charge_schedules_charge_day_range")
        ),
        sa.CheckConstraint(
            "due_days BETWEEN 0 AND 60", name=op.f("ck_charge_schedules_due_days_range")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_charge_schedules_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charge_schedules")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_charge_schedules_site_id_id")),
        sa.UniqueConstraint("site_id", name=op.f("uq_charge_schedules_site_id")),
    )
    op.create_index(
        op.f("ix_charge_schedules_site_id"), "charge_schedules", ["site_id"], unique=False
    )
    op.create_table(
        "charge_schedule_runs",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("charge_run_id", sa.Uuid(), nullable=True),
        sa.Column("ran_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('posted', 'skipped', 'failed')", name=op.f("ck_charge_schedule_runs_status")
        ),
        sa.CheckConstraint(
            "month BETWEEN 1 AND 12", name=op.f("ck_charge_schedule_runs_month_range")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "charge_run_id"],
            ["charge_runs.site_id", "charge_runs.id"],
            name=op.f("fk_charge_schedule_runs_site_id_charge_run_id_charge_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_charge_schedule_runs_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charge_schedule_runs")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_charge_schedule_runs_site_id_id")),
        sa.UniqueConstraint(
            "site_id", "year", "month", name=op.f("uq_charge_schedule_runs_site_id_year_month")
        ),
    )
    op.create_index(
        op.f("ix_charge_schedule_runs_site_id"), "charge_schedule_runs", ["site_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in TABLES:
        enable_tenant_rls(op, table)


def downgrade() -> None:
    for table in TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_charge_schedule_runs_site_id"), table_name="charge_schedule_runs")
    op.drop_table("charge_schedule_runs")
    op.drop_index(op.f("ix_charge_schedules_site_id"), table_name="charge_schedules")
    op.drop_table("charge_schedules")
    # ### end Alembic commands ###
