"""Sitede modül durumu (site_modules) — modül kapısı.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 21:31:13.519340

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_modules",
        sa.Column("module_key", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "module_key IN ('finance', 'announcements', 'requests', 'visitors', 'packages', 'documents', 'reservations', 'valet', 'general-assembly', 'surveys', 'staff', 'portfolio')",
            name=op.f("ck_site_modules_module_key"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_site_modules_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_modules")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_site_modules_site_id_id")),
        sa.UniqueConstraint(
            "site_id", "module_key", name=op.f("uq_site_modules_site_id_module_key")
        ),
    )
    op.create_index(op.f("ix_site_modules_site_id"), "site_modules", ["site_id"], unique=False)
    # ### end Alembic commands ###

    enable_tenant_rls(op, "site_modules")


def downgrade() -> None:
    disable_tenant_rls(op, "site_modules")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_modules_site_id"), table_name="site_modules")
    op.drop_table("site_modules")
    # ### end Alembic commands ###
