"""Finans: kurallar, bütçe (işletme projesi), cari defter, özet bakiye, tahakkuk, idempotency.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-30 23:41:34.349921

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.

Değişmez defterler (docs/04 §8): ledger_entries, charges, charge_lines satırlarına UPDATE ve
DELETE tetikleyiciyle reddedilir — uygulama katmanında unutulsa bile.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "periods",
    "expense_categories",
    "charge_types",
    "allocation_rules",
    "allocation_components",
    "unit_weights",
    "budget_plans",
    "budget_items",
    "late_fee_policies",
    "ledger_entries",
    "account_balances",
    "charge_runs",
    "charges",
    "charge_lines",
    "idempotency_keys",
)
IMMUTABLE_TABLES = ("ledger_entries", "charges", "charge_lines")

_FORBID_CHANGE = """
CREATE OR REPLACE FUNCTION forbid_financial_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Finansal kayıt değiştirilemez ve silinemez (%); düzeltme ters kayıtla yapılır.',
        TG_TABLE_NAME USING ERRCODE = 'restrict_violation';
END
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_rules",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("fixed_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("area_basis", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(kind = 'fixed_per_unit') = (fixed_amount IS NOT NULL)",
            name=op.f("ck_allocation_rules_fixed_amount"),
        ),
        sa.CheckConstraint(
            "area_basis IN ('gross', 'net')", name=op.f("ck_allocation_rules_area_basis")
        ),
        sa.CheckConstraint(
            "kind IN ('equal', 'by_land_share', 'by_area', 'by_unit_type_weight', 'by_custom_weight', 'fixed_per_unit', 'by_meter_consumption', 'composite')",
            name=op.f("ck_allocation_rules_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_allocation_rules_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_rules")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_allocation_rules_site_id_id")),
    )
    op.create_index(
        op.f("ix_allocation_rules_site_id"), "allocation_rules", ["site_id"], unique=False
    )
    op.create_table(
        "budget_plans",
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("notified_on", sa.Date(), nullable=True),
        sa.Column("objection_deadline", sa.Date(), nullable=True),
        sa.Column("finalized_on", sa.Date(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'notified', 'finalized', 'superseded')",
            name=op.f("ck_budget_plans_status"),
        ),
        sa.CheckConstraint(
            "fiscal_year BETWEEN 2000 AND 2100", name=op.f("ck_budget_plans_fiscal_year")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_budget_plans_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_plans")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_budget_plans_site_id_id")),
    )
    op.create_index(op.f("ix_budget_plans_site_id"), "budget_plans", ["site_id"], unique=False)
    op.create_table(
        "charge_types",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("payer_rule", sa.Text(), nullable=False),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("is_advance", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "payer_rule IN ('occupant', 'owner')", name=op.f("ck_charge_types_payer_rule")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_charge_types_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charge_types")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_charge_types_site_id_id")),
    )
    op.create_index(op.f("ix_charge_types_site_id"), "charge_types", ["site_id"], unique=False)
    op.create_table(
        "expense_categories",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('operating', 'capital_improvement')", name=op.f("ck_expense_categories_kind")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_expense_categories_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_categories")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_expense_categories_site_id_id")),
    )
    op.create_index(
        op.f("ix_expense_categories_site_id"), "expense_categories", ["site_id"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_idempotency_keys_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_idempotency_keys_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_idempotency_keys_site_id_id")),
        sa.UniqueConstraint(
            "site_id", "user_id", "key", name=op.f("uq_idempotency_keys_site_id_user_id_key")
        ),
    )
    op.create_index(
        op.f("ix_idempotency_keys_site_id"), "idempotency_keys", ["site_id"], unique=False
    )
    op.create_table(
        "late_fee_policies",
        sa.Column("monthly_rate_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("grace_days", sa.Integer(), nullable=False),
        sa.Column("minimum_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("grace_days >= 0", name=op.f("ck_late_fee_policies_grace_days")),
        sa.CheckConstraint("monthly_rate_percent >= 0", name=op.f("ck_late_fee_policies_rate")),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_late_fee_policies_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_late_fee_policies")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_late_fee_policies_site_id_id")),
        sa.UniqueConstraint("site_id", name=op.f("uq_late_fee_policies_site_id")),
    )
    op.create_index(
        op.f("ix_late_fee_policies_site_id"), "late_fee_policies", ["site_id"], unique=False
    )
    op.create_table(
        "periods",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_periods_status")),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name=op.f("ck_periods_month_range")),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_periods_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_periods")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_periods_site_id_id")),
        sa.UniqueConstraint("site_id", "year", "month", name=op.f("uq_periods_site_id_year_month")),
    )
    op.create_index(op.f("ix_periods_site_id"), "periods", ["site_id"], unique=False)
    op.create_table(
        "allocation_components",
        sa.Column("allocation_rule_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("area_basis", sa.Text(), nullable=False),
        sa.Column("percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "area_basis IN ('gross', 'net')", name=op.f("ck_allocation_components_area_basis")
        ),
        sa.CheckConstraint(
            "kind IN ('equal', 'by_land_share', 'by_area', 'by_unit_type_weight', 'by_custom_weight', 'fixed_per_unit', 'by_meter_consumption', 'composite')",
            name=op.f("ck_allocation_components_kind"),
        ),
        sa.CheckConstraint(
            "kind NOT IN ('composite', 'fixed_per_unit')",
            name=op.f("ck_allocation_components_component_kind"),
        ),
        sa.CheckConstraint(
            "percent > 0 AND percent <= 100", name=op.f("ck_allocation_components_percent")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "allocation_rule_id"],
            ["allocation_rules.site_id", "allocation_rules.id"],
            name=op.f("fk_allocation_components_site_id_allocation_rule_id_allocation_rules"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_allocation_components_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_components")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_allocation_components_site_id_id")),
    )
    op.create_index(
        op.f("ix_allocation_components_allocation_rule_id"),
        "allocation_components",
        ["allocation_rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_allocation_components_site_id"), "allocation_components", ["site_id"], unique=False
    )
    op.create_table(
        "budget_items",
        sa.Column("budget_plan_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("expense_category_id", sa.Uuid(), nullable=False),
        sa.Column("charge_type_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_rule_id", sa.Uuid(), nullable=False),
        sa.Column("annual_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("frequency", sa.Text(), nullable=False),
        sa.Column("scope_kind", sa.Text(), nullable=False),
        sa.Column("scope_block_ids", sa.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("scope_unit_type_ids", sa.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("scope_usage", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "frequency IN ('monthly', 'quarterly', 'yearly', 'one_time')",
            name=op.f("ck_budget_items_frequency"),
        ),
        sa.CheckConstraint(
            "scope_kind IN ('whole_site', 'blocks', 'unit_types', 'usage')",
            name=op.f("ck_budget_items_scope_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "allocation_rule_id"],
            ["allocation_rules.site_id", "allocation_rules.id"],
            name=op.f("fk_budget_items_site_id_allocation_rule_id_allocation_rules"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "budget_plan_id"],
            ["budget_plans.site_id", "budget_plans.id"],
            name=op.f("fk_budget_items_site_id_budget_plan_id_budget_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "charge_type_id"],
            ["charge_types.site_id", "charge_types.id"],
            name=op.f("fk_budget_items_site_id_charge_type_id_charge_types"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "expense_category_id"],
            ["expense_categories.site_id", "expense_categories.id"],
            name=op.f("fk_budget_items_site_id_expense_category_id_expense_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_budget_items_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_items")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_budget_items_site_id_id")),
    )
    op.create_index(
        op.f("ix_budget_items_budget_plan_id"), "budget_items", ["budget_plan_id"], unique=False
    )
    op.create_index(op.f("ix_budget_items_site_id"), "budget_items", ["site_id"], unique=False)
    op.create_table(
        "charge_runs",
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("budget_plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("charge_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by", sa.Text(), nullable=True),
        sa.Column("reversal_of_run_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'posted', 'reversed')", name=op.f("ck_charge_runs_status")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "budget_plan_id"],
            ["budget_plans.site_id", "budget_plans.id"],
            name=op.f("fk_charge_runs_site_id_budget_plan_id_budget_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "period_id"],
            ["periods.site_id", "periods.id"],
            name=op.f("fk_charge_runs_site_id_period_id_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "reversal_of_run_id"],
            ["charge_runs.site_id", "charge_runs.id"],
            name=op.f("fk_charge_runs_site_id_reversal_of_run_id_charge_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_charge_runs_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charge_runs")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_charge_runs_site_id_id")),
    )
    op.create_index(op.f("ix_charge_runs_site_id"), "charge_runs", ["site_id"], unique=False)
    op.create_index(
        "uq_charge_runs_reversal_of",
        "charge_runs",
        ["reversal_of_run_id"],
        unique=True,
        postgresql_where=sa.text("reversal_of_run_id IS NOT NULL"),
    )
    op.create_index(
        "uq_charge_runs_valid_period",
        "charge_runs",
        ["site_id", "period_id"],
        unique=True,
        postgresql_where=sa.text("status = 'posted' AND reversal_of_run_id IS NULL"),
    )
    op.create_table(
        "unit_weights",
        sa.Column("allocation_rule_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("weight >= 0", name=op.f("ck_unit_weights_weight")),
        sa.ForeignKeyConstraint(
            ["site_id", "allocation_rule_id"],
            ["allocation_rules.site_id", "allocation_rules.id"],
            name=op.f("fk_unit_weights_site_id_allocation_rule_id_allocation_rules"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_unit_weights_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_unit_weights_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_weights")),
        sa.UniqueConstraint(
            "allocation_rule_id", "unit_id", name=op.f("uq_unit_weights_allocation_rule_id_unit_id")
        ),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_unit_weights_site_id_id")),
    )
    op.create_index(op.f("ix_unit_weights_site_id"), "unit_weights", ["site_id"], unique=False)
    op.create_table(
        "account_balances",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("debit_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("credit_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("oldest_open_due_date", sa.Date(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id", "account_id"],
            ["ledger_accounts.site_id", "ledger_accounts.id"],
            name=op.f("fk_account_balances_site_id_account_id_ledger_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_account_balances_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_balances")),
        sa.UniqueConstraint("account_id", name=op.f("uq_account_balances_account_id")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_account_balances_site_id_id")),
    )
    op.create_index(
        "ix_account_balances_site_balance", "account_balances", ["site_id", "balance"], unique=False
    )
    op.create_index(
        op.f("ix_account_balances_site_id"), "account_balances", ["site_id"], unique=False
    )
    op.create_table(
        "charges",
        sa.Column("charge_run_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("ledger_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id", "charge_run_id"],
            ["charge_runs.site_id", "charge_runs.id"],
            name=op.f("fk_charges_site_id_charge_run_id_charge_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "ledger_account_id"],
            ["ledger_accounts.site_id", "ledger_accounts.id"],
            name=op.f("fk_charges_site_id_ledger_account_id_ledger_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_charges_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_charges_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charges")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_charges_site_id_id")),
    )
    op.create_index(op.f("ix_charges_charge_run_id"), "charges", ["charge_run_id"], unique=False)
    op.create_index(
        op.f("ix_charges_ledger_account_id"), "charges", ["ledger_account_id"], unique=False
    )
    op.create_index(op.f("ix_charges_site_id"), "charges", ["site_id"], unique=False)
    op.create_table(
        "ledger_entries",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("debit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reversal_of_entry_id", sa.Uuid(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source IN ('charge', 'payment', 'late_fee', 'adjustment', 'transfer', 'advance')",
            name=op.f("ck_ledger_entries_source"),
        ),
        sa.CheckConstraint(
            "debit >= 0 AND credit >= 0 AND (debit > 0) <> (credit > 0)",
            name=op.f("ck_ledger_entries_one_side"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "account_id"],
            ["ledger_accounts.site_id", "ledger_accounts.id"],
            name=op.f("fk_ledger_entries_site_id_account_id_ledger_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "reversal_of_entry_id"],
            ["ledger_entries.site_id", "ledger_entries.id"],
            name=op.f("fk_ledger_entries_site_id_reversal_of_entry_id_ledger_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_ledger_entries_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_ledger_entries_site_id_id")),
    )
    op.create_index(
        "ix_ledger_entries_site_account_date",
        "ledger_entries",
        ["site_id", "account_id", "date"],
        unique=False,
    )
    op.create_index(op.f("ix_ledger_entries_site_id"), "ledger_entries", ["site_id"], unique=False)
    op.create_index(
        "ix_ledger_entries_source", "ledger_entries", ["site_id", "source_id"], unique=False
    )
    op.create_index(
        "uq_ledger_entries_reversal_of",
        "ledger_entries",
        ["reversal_of_entry_id"],
        unique=True,
        postgresql_where=sa.text("reversal_of_entry_id IS NOT NULL"),
    )
    op.create_table(
        "charge_lines",
        sa.Column("charge_id", sa.Uuid(), nullable=False),
        sa.Column("budget_item_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("allocation_kind", sa.Text(), nullable=False),
        sa.Column("weight", sa.Numeric(), nullable=True),
        sa.Column("weight_total", sa.Numeric(), nullable=True),
        sa.Column("source_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "allocation_kind IN ('equal', 'by_land_share', 'by_area', 'by_unit_type_weight', 'by_custom_weight', 'fixed_per_unit', 'by_meter_consumption', 'composite')",
            name=op.f("ck_charge_lines_allocation_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "budget_item_id"],
            ["budget_items.site_id", "budget_items.id"],
            name=op.f("fk_charge_lines_site_id_budget_item_id_budget_items"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "charge_id"],
            ["charges.site_id", "charges.id"],
            name=op.f("fk_charge_lines_site_id_charge_id_charges"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_charge_lines_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charge_lines")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_charge_lines_site_id_id")),
    )
    op.create_index(
        "ix_charge_lines_budget_item", "charge_lines", ["site_id", "budget_item_id"], unique=False
    )
    op.create_index(op.f("ix_charge_lines_charge_id"), "charge_lines", ["charge_id"], unique=False)
    op.create_index(op.f("ix_charge_lines_site_id"), "charge_lines", ["site_id"], unique=False)
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_tenant_rls(op, table)
    op.execute(_FORBID_CHANGE)
    for table in IMMUTABLE_TABLES:
        op.execute(
            f'CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON "{table}" '
            "FOR EACH ROW EXECUTE FUNCTION forbid_financial_change()"
        )


def downgrade() -> None:
    for table in IMMUTABLE_TABLES:
        op.execute(f'DROP TRIGGER IF EXISTS {table}_immutable ON "{table}"')
    op.execute("DROP FUNCTION IF EXISTS forbid_financial_change()")
    for table in TENANT_TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_charge_lines_site_id"), table_name="charge_lines")
    op.drop_index(op.f("ix_charge_lines_charge_id"), table_name="charge_lines")
    op.drop_index("ix_charge_lines_budget_item", table_name="charge_lines")
    op.drop_table("charge_lines")
    op.drop_index(
        "uq_ledger_entries_reversal_of",
        table_name="ledger_entries",
        postgresql_where=sa.text("reversal_of_entry_id IS NOT NULL"),
    )
    op.drop_index("ix_ledger_entries_source", table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_site_id"), table_name="ledger_entries")
    op.drop_index("ix_ledger_entries_site_account_date", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_charges_site_id"), table_name="charges")
    op.drop_index(op.f("ix_charges_ledger_account_id"), table_name="charges")
    op.drop_index(op.f("ix_charges_charge_run_id"), table_name="charges")
    op.drop_table("charges")
    op.drop_index(op.f("ix_account_balances_site_id"), table_name="account_balances")
    op.drop_index("ix_account_balances_site_balance", table_name="account_balances")
    op.drop_table("account_balances")
    op.drop_index(op.f("ix_unit_weights_site_id"), table_name="unit_weights")
    op.drop_table("unit_weights")
    op.drop_index(
        "uq_charge_runs_valid_period",
        table_name="charge_runs",
        postgresql_where=sa.text("status = 'posted' AND reversal_of_run_id IS NULL"),
    )
    op.drop_index(
        "uq_charge_runs_reversal_of",
        table_name="charge_runs",
        postgresql_where=sa.text("reversal_of_run_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_charge_runs_site_id"), table_name="charge_runs")
    op.drop_table("charge_runs")
    op.drop_index(op.f("ix_budget_items_site_id"), table_name="budget_items")
    op.drop_index(op.f("ix_budget_items_budget_plan_id"), table_name="budget_items")
    op.drop_table("budget_items")
    op.drop_index(op.f("ix_allocation_components_site_id"), table_name="allocation_components")
    op.drop_index(
        op.f("ix_allocation_components_allocation_rule_id"), table_name="allocation_components"
    )
    op.drop_table("allocation_components")
    op.drop_index(op.f("ix_periods_site_id"), table_name="periods")
    op.drop_table("periods")
    op.drop_index(op.f("ix_late_fee_policies_site_id"), table_name="late_fee_policies")
    op.drop_table("late_fee_policies")
    op.drop_index(op.f("ix_idempotency_keys_site_id"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_expense_categories_site_id"), table_name="expense_categories")
    op.drop_table("expense_categories")
    op.drop_index(op.f("ix_charge_types_site_id"), table_name="charge_types")
    op.drop_table("charge_types")
    op.drop_index(op.f("ix_budget_plans_site_id"), table_name="budget_plans")
    op.drop_table("budget_plans")
    op.drop_index(op.f("ix_allocation_rules_site_id"), table_name="allocation_rules")
    op.drop_table("allocation_rules")
    # ### end Alembic commands ###
