"""Kişiler (persons), bölüm–kişi ilişkisi (unit_parties), cari hesaplar (ledger_accounts).

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 22:40:24.502677

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("persons", "unit_parties", "ledger_accounts")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("search_name", sa.Text(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "phone IS NULL OR phone ~ '^\\+90[5][0-9]{9}$'", name=op.f("ck_persons_phone_e164")
        ),
        sa.CheckConstraint(
            "char_length(first_name) BETWEEN 2 AND 40", name=op.f("ck_persons_first_name_length")
        ),
        sa.CheckConstraint(
            "char_length(last_name) BETWEEN 2 AND 40", name=op.f("ck_persons_last_name_length")
        ),
        sa.CheckConstraint(
            "email IS NULL OR email = lower(email)", name=op.f("ck_persons_email_lowercase")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_persons_site_id_sites")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_persons_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persons")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_persons_site_id_id")),
    )
    op.create_index(op.f("ix_persons_search_name"), "persons", ["search_name"], unique=False)
    op.create_index(op.f("ix_persons_site_id"), "persons", ["site_id"], unique=False)
    op.create_table(
        "ledger_accounts",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("reference_code", sa.Text(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('owner', 'occupant')", name=op.f("ck_ledger_accounts_kind")),
        sa.ForeignKeyConstraint(
            ["site_id", "person_id"],
            ["persons.site_id", "persons.id"],
            name=op.f("fk_ledger_accounts_site_id_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_ledger_accounts_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_ledger_accounts_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_accounts")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_ledger_accounts_site_id_id")),
        sa.UniqueConstraint(
            "site_id", "reference_code", name=op.f("uq_ledger_accounts_site_id_reference_code")
        ),
        sa.UniqueConstraint(
            "unit_id", "person_id", "kind", name=op.f("uq_ledger_accounts_unit_id_person_id_kind")
        ),
    )
    op.create_index(
        op.f("ix_ledger_accounts_site_id"), "ledger_accounts", ["site_id"], unique=False
    )
    op.create_table(
        "unit_parties",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("share_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner', 'tenant', 'resident', 'proxy')", name=op.f("ck_unit_parties_role")
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date", name=op.f("ck_unit_parties_date_range")
        ),
        sa.CheckConstraint(
            "share_percent > 0 AND share_percent <= 100", name=op.f("ck_unit_parties_share_percent")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "person_id"],
            ["persons.site_id", "persons.id"],
            name=op.f("fk_unit_parties_site_id_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "unit_id"],
            ["units.site_id", "units.id"],
            name=op.f("fk_unit_parties_site_id_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_unit_parties_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_parties")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_unit_parties_site_id_id")),
    )
    op.create_index(op.f("ix_unit_parties_person_id"), "unit_parties", ["person_id"], unique=False)
    op.create_index(op.f("ix_unit_parties_site_id"), "unit_parties", ["site_id"], unique=False)
    op.create_index(op.f("ix_unit_parties_unit_id"), "unit_parties", ["unit_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_site_memberships_site_id_person_id_persons"),
        "site_memberships",
        "persons",
        ["site_id", "person_id"],
        ["site_id", "id"],
    )
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_tenant_rls(op, table)


def downgrade() -> None:
    for table in TENANT_TABLES:
        disable_tenant_rls(op, table)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_site_memberships_site_id_person_id_persons"),
        "site_memberships",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_unit_parties_unit_id"), table_name="unit_parties")
    op.drop_index(op.f("ix_unit_parties_site_id"), table_name="unit_parties")
    op.drop_index(op.f("ix_unit_parties_person_id"), table_name="unit_parties")
    op.drop_table("unit_parties")
    op.drop_index(op.f("ix_ledger_accounts_site_id"), table_name="ledger_accounts")
    op.drop_table("ledger_accounts")
    op.drop_index(op.f("ix_persons_site_id"), table_name="persons")
    op.drop_index(op.f("ix_persons_search_name"), table_name="persons")
    op.drop_table("persons")
    # ### end Alembic commands ###
