"""İade (refunds) — değişmez (forbid_financial_change); defter ve kasa kaynak türü `refund`.

Geri alma, `refund` hareketi varsa durur (finansal kayıt silinmez).

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-03 12:48:40.386677

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

_LEDGER = ("charge", "payment", "late_fee", "adjustment", "transfer", "advance", "opening")
_CASH = ("manual", "payment", "expense", "transfer", "opening")


def _source_check(table: str, values: tuple[str, ...]) -> None:
    name = op.f(f"ck_{table}_source")
    op.drop_constraint(name, table, type_="check")
    allowed = ", ".join(f"'{v}'" for v in values)
    op.create_check_constraint(name, table, f"source IN ({allowed})")


revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refunds",
        sa.Column("ledger_account_id", sa.Uuid(), nullable=False),
        sa.Column("cash_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by_name", sa.Text(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_refunds_amount_positive")),
        sa.ForeignKeyConstraint(
            ["site_id", "cash_account_id"],
            ["cash_accounts.site_id", "cash_accounts.id"],
            name=op.f("fk_refunds_site_id_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "ledger_account_id"],
            ["ledger_accounts.site_id", "ledger_accounts.id"],
            name=op.f("fk_refunds_site_id_ledger_account_id_ledger_accounts"),
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_refunds_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_refunds_site_id_id")),
    )
    op.create_index(
        op.f("ix_refunds_ledger_account_id"), "refunds", ["ledger_account_id"], unique=False
    )
    op.create_index(op.f("ix_refunds_site_id"), "refunds", ["site_id"], unique=False)
    # ### end Alembic commands ###

    enable_tenant_rls(op, "refunds")
    op.execute(
        'CREATE TRIGGER refunds_immutable BEFORE UPDATE OR DELETE ON "refunds" '
        "FOR EACH ROW EXECUTE FUNCTION forbid_financial_change()"
    )
    _source_check("ledger_entries", (*_LEDGER, "refund"))
    _source_check("cash_movements", (*_CASH, "refund"))


def downgrade() -> None:
    _source_check("cash_movements", _CASH)
    _source_check("ledger_entries", _LEDGER)
    op.execute('DROP TRIGGER IF EXISTS refunds_immutable ON "refunds"')
    disable_tenant_rls(op, "refunds")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refunds_site_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_ledger_account_id"), table_name="refunds")
    op.drop_table("refunds")
    # ### end Alembic commands ###
