"""Banka hareketi aktarımı (bank_imports, bank_import_lines) ve tekrarlanan gider
(recurring_expenses, recurring_expense_runs).

Aktarılmış banka hareketi değişmez (forbid_financial_change); önizleme ve tanımlar düzenlenir.

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-05 20:17:40.323016

Kiracı tablosu ekliyorsan: enable_tenant_rls(op, "tablo") — docs/02-mimari.md §3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from site_yonetim.db.rls import disable_tenant_rls, enable_tenant_rls

TABLES = ("bank_imports", "bank_import_lines", "recurring_expenses", "recurring_expense_runs")

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_imports",
        sa.Column("cash_account_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed')", name=op.f("ck_bank_imports_status")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "cash_account_id"],
            ["cash_accounts.site_id", "cash_accounts.id"],
            name=op.f("fk_bank_imports_site_id_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_bank_imports_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_bank_imports_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_imports")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_bank_imports_site_id_id")),
    )
    op.create_index(op.f("ix_bank_imports_site_id"), "bank_imports", ["site_id"], unique=False)
    op.create_table(
        "recurring_expenses",
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("expense_category_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("vendor", sa.Text(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("auto_pay", sa.Boolean(), nullable=False),
        sa.Column("cash_account_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("active_since", sa.Date(), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT auto_pay OR cash_account_id IS NOT NULL",
            name=op.f("ck_recurring_expenses_auto_pay_account"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_recurring_expenses_amount_positive")),
        sa.CheckConstraint(
            "day_of_month BETWEEN 1 AND 28", name=op.f("ck_recurring_expenses_day_range")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "cash_account_id"],
            ["cash_accounts.site_id", "cash_accounts.id"],
            name=op.f("fk_recurring_expenses_site_id_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "expense_category_id"],
            ["expense_categories.site_id", "expense_categories.id"],
            name=op.f("fk_recurring_expenses_site_id_expense_category_id_expense_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_recurring_expenses_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_expenses")),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_recurring_expenses_site_id_id")),
    )
    op.create_index(
        op.f("ix_recurring_expenses_site_id"), "recurring_expenses", ["site_id"], unique=False
    )
    op.create_table(
        "recurring_expense_runs",
        sa.Column("recurring_expense_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("expense_id", sa.Uuid(), nullable=True),
        sa.Column("ran_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('created', 'skipped', 'failed')",
            name=op.f("ck_recurring_expense_runs_status"),
        ),
        sa.CheckConstraint(
            "month BETWEEN 1 AND 12", name=op.f("ck_recurring_expense_runs_month_range")
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "expense_id"],
            ["expenses.site_id", "expenses.id"],
            name=op.f("fk_recurring_expense_runs_site_id_expense_id_expenses"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "recurring_expense_id"],
            ["recurring_expenses.site_id", "recurring_expenses.id"],
            name=op.f("fk_recurring_expense_runs_site_id_recurring_expense_id_recurring_expenses"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_recurring_expense_runs_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_expense_runs")),
        sa.UniqueConstraint(
            "recurring_expense_id",
            "year",
            "month",
            name=op.f("uq_recurring_expense_runs_recurring_expense_id_year_month"),
        ),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_recurring_expense_runs_site_id_id")),
    )
    op.create_index(
        op.f("ix_recurring_expense_runs_recurring_expense_id"),
        "recurring_expense_runs",
        ["recurring_expense_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_expense_runs_site_id"),
        "recurring_expense_runs",
        ["site_id"],
        unique=False,
    )
    op.create_table(
        "bank_import_lines",
        sa.Column("cash_account_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("bank_import_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id", "bank_import_id"],
            ["bank_imports.site_id", "bank_imports.id"],
            name=op.f("fk_bank_import_lines_site_id_bank_import_id_bank_imports"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "cash_account_id"],
            ["cash_accounts.site_id", "cash_accounts.id"],
            name=op.f("fk_bank_import_lines_site_id_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id", "payment_id"],
            ["payments.site_id", "payments.id"],
            name=op.f("fk_bank_import_lines_site_id_payment_id_payments"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_bank_import_lines_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_import_lines")),
        sa.UniqueConstraint(
            "site_id",
            "cash_account_id",
            "fingerprint",
            name=op.f("uq_bank_import_lines_site_id_cash_account_id_fingerprint"),
        ),
        sa.UniqueConstraint("site_id", "id", name=op.f("uq_bank_import_lines_site_id_id")),
    )
    op.create_index(
        op.f("ix_bank_import_lines_site_id"), "bank_import_lines", ["site_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in TABLES:
        enable_tenant_rls(op, table)
    op.execute(
        'CREATE TRIGGER bank_import_lines_immutable BEFORE UPDATE OR DELETE ON "bank_import_lines" '
        "FOR EACH ROW EXECUTE FUNCTION forbid_financial_change()"
    )


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS bank_import_lines_immutable ON "bank_import_lines"')
    for table in TABLES:
        disable_tenant_rls(op, table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bank_import_lines_site_id"), table_name="bank_import_lines")
    op.drop_table("bank_import_lines")
    op.drop_index(op.f("ix_recurring_expense_runs_site_id"), table_name="recurring_expense_runs")
    op.drop_index(
        op.f("ix_recurring_expense_runs_recurring_expense_id"), table_name="recurring_expense_runs"
    )
    op.drop_table("recurring_expense_runs")
    op.drop_index(op.f("ix_recurring_expenses_site_id"), table_name="recurring_expenses")
    op.drop_table("recurring_expenses")
    op.drop_index(op.f("ix_bank_imports_site_id"), table_name="bank_imports")
    op.drop_table("bank_imports")
    # ### end Alembic commands ###
